"""update author and post table

Revision ID: c17166bcbce0
Revises: 6c76ffcefdf1
Create Date: 2023-09-26 15:57:47.408162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17166bcbce0'
down_revision: Union[str, None] = '6c76ffcefdf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('username', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'author', ['username'])
    op.drop_column('author', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'author', type_='unique')
    op.drop_column('author', 'username')
    # ### end Alembic commands ###
